[package]
name = "shadow-risc0-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
hex.workspace = true
shadow-proof-core = { path = "../crates/shadow-proof-core" }
shadow-prover-lib = { path = "../crates/shadow-prover-lib" }
