[package]
name = "shadow-risc0-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
clap.workspace = true
hex.workspace = true
risc0-zkvm = { workspace = true, features = ["client", "prove"] }
serde.workspace = true
serde_json.workspace = true
shadow-proof-core = { path = "../crates/shadow-proof-core" }
shadow-risc0-methods = { path = "../methods" }
