[profile.default]
src = 'src'
test = 'test'
scripts = 'script'
libs = ['node_modules']
optimizer = true
optimizer_runs = 200
evm_version = 'shanghai'
bytecode_hash = 'ipfs'
solc_version = '0.8.33'
via_ir = true
fs_permissions = [{ access = "read", path = "./" }]

remappings = [
  'forge-std/=node_modules/forge-std/src/',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/'
]
