[package]
name = "shadow-risc0-methods"
version.workspace = true
edition.workspace = true
license.workspace = true

[build-dependencies]
risc0-build.workspace = true

[package.metadata.risc0]
methods = ["guest"]
